# Generated by Django 4.2.4 on 2023-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='Something', max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='First',
            field=models.CharField(default='Something', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='Last',
            field=models.CharField(default='Something', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
