# Generated by Django 4.2.4 on 2023-08-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_employee_email_employee_first_employee_last_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
