# Generated by Django 4.2.4 on 2023-08-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_poste_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prénom', models.CharField(blank=True, max_length=30, null=True)),
                ('Nom', models.CharField(blank=True, max_length=30, null=True)),
                ('Date_Naissance', models.DateField(blank=True, null=True)),
                ('Lieu_Naissance', models.CharField(blank=True, max_length=40, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=60, null=True)),
                ('Echelon', models.SmallIntegerField(blank=True, null=True)),
                ('Categorie', models.SmallIntegerField(blank=True, null=True)),
                ('Salaire_de_Base', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('CIN', models.CharField(blank=True, max_length=8)),
                ('Id_Banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.banque')),
                ('Id_Etat_Contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.etat_contrat')),
                ('Id_Local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.local')),
                ('Id_Poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.poste')),
            ],
        ),
    ]
